version: '3'
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRE_DB: portal
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: APowerfulPassword1234