version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - 3305:3305
    environment:
      MYSQL_ROOT_HOST: "localhost"
      MYSQL_ROOT_PASSWORD: "dbrootpass"
      MYSQL_DATABASE: "db_portal"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "APowerfulPassword1234"
    restart: always